---
basic-shadow-chameleon-GIN:
  attack: "basic-shadow"
  dataset: "chameleon"
  split: "sampled"
  model: "GIN"
  epochs_target: 200
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  batch_size: 32
  lr: 0.001
  dropout: 0.2
  query_hops: 2
confidence-chameleon-GIN:
  attack: "confidence"
  dataset: "chameleon"
  split: "sampled"
  model: "GIN"
  epochs_target: 200
  hidden_dim_target: 256
  lr: 0.001
  dropout: 0.2
  query_hops: 2
LiRA-chameleon-GIN:
  attack: "lira"
  dataset: "chameleon"
  model: "GIN"
  epochs_target: 200
  hidden_dim_target: 256
  num_shadow_models: 128
  lr: 0.001
  dropout: 0.2
  query_hops: 2
RMIA-chameleon-GIN:
  attack: "rmia"
  dataset: "chameleon"
  model: "GIN"
  epochs_target: 200
  hidden_dim_target: 256
  num_shadow_models: 128
  lr: 0.001
  dropout: 0.2
  query_hops: 2
  rmia_offline_interp_param: 0.6
