---
confidence-flickr-GraphSAGE:
  attack: "confidence"
  dataset: "flickr"
  model: "GraphSAGE"
  epochs_target: 500
  experiments: 10
  hidden_dim_target: [1024]
  num_shadow_models: 128
  query_hops: [0, 2]
  transductive: false
  target_fpr: 0.005
  lr: 0.001
  weight_decay: 0.0005
  dropout: 0.25
lira-flickr-GraphSAGE:
  attack: "lira"
  dataset: "flickr"
  model: "GraphSAGE"
  epochs_target: 500
  experiments: 10
  hidden_dim_target: [1024]
  num_shadow_models: 128
  query_hops: [0, 2]
  transductive: false
  target_fpr: 0.005
  lr: 0.001
  weight_decay: 0.0005
  dropout: 0.25
