---
cora-GCN:
  dataset: "cora"
  model: "GCN"
  epochs: 15
  hidden_dim: [32]
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  max_num_nodes: null
  num_audits: 1
  target_fpr: [0.01, 0.005]
  attacks:
    lset:
      attack: "lset"
      num_shadow_models: 10
      epochs: 15
    confidence:
      attack: "confidence"
      hidden_dim: [64]
    lira:
      attack: "lira"
      num_shadow_models: 10