---
LiRA-flickr-GCN-0hop:
  attack: "lira"
  dataset: "flickr"
  model: "GCN"
  epochs_target: 500
  hidden_dim_target: [64]
  num_shadow_models: 128
  query_hops: 0
  transductive: false
  target_fpr: 0.001
LiRA-flickr-GCN-2hop:
  attack: "lira"
  dataset: "flickr"
  model: "GCN"
  epochs_target: 500
  hidden_dim_target: [64]
  num_shadow_models: 128
  query_hops: 2
  transductive: false
  target_fpr: 0.001
