---
lset-reddit-GCN:
  attack: "lset"
  dataset: "reddit"
  max_num_nodes: 3000
  model: "GCN"
  epochs_target: 100
  epochs_shadow: 100
  num_experiments: 3
  hidden_dim_target: [32]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  num_shadow_models: 10
lira-reddit-GCN:
  attack: "lira"
  dataset: "reddit"
  max_num_nodes: 3000
  model: "GCN"
  epochs_target: 100
  epochs_shadow: 100
  num_experiments: 3
  hidden_dim_target: [32]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  num_shadow_models: 10
rmia-reddit-GCN:
  attack: "rmia"
  dataset: "reddit"
  max_num_nodes: 3000
  model: "GCN"
  epochs_target: 100
  epochs_shadow: 100
  num_experiments: 3
  hidden_dim_target: [32]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  num_shadow_models: 10
