---
cora-GCN:
  dataset: "cora"
  model: "GCN"
  epochs: 200
  hidden_dim:
  - 64
  lr: 0.001
  weight_decay: 0.00001
  dropout: 0.5
  max_num_nodes: null
  frac_target_nodes: 0.5
  train_frac: 0.5
  val_frac: 0.0
  num_audits: 10
  target_fpr:
  - 0.01
  - 0.001
  pretrain_shadow_models: true
  num_shadow_models: 8
  seed: 0
  attacks:
    lira:
      attack: "lira"
    rmia:
      attack: "rmia"
      rmia_gamma: 1
      Z_frac: 0.5
    base:
      attack: "base"
