---
citeseer-GAT:
  dataset: "citeseer"
  model: "GAT"
  epochs: 50
  batch_size: 8192
  hidden_dim:
  - 64
  lr: 0.001
  weight_decay: 0.0001
  dropout: 0.5
  max_num_nodes: null
  frac_target_nodes: 0.5
  train_frac: 0.5
  val_frac: 0.0
  num_audits: 20
  target_fpr:
  - 0.01
  pretrain_shadow_models: True
  num_shadow_models: 8
  seed: 0
  attacks:
    lira:
      attack: "lira"
    rmia:
      attack: "rmia"
      rmia_gamma: 1
      Z_frac: 1.0
    base:
      attack: "base"
    g-base-MIA:
      attack: "g-base"
      num_sampled_graphs: 8
      sampling_strategy: "MIA"
      prior: 0.5
    lira-offline:
      attack: "lira"
      offline: True
    rmia-offline:
      attack: "rmia"
      rmia_gamma: 1
      Z_frac: 0.5
      offline: True
    base-offline:
      attack: "base"
      offline: True
    g-base-MIA-offline:
      attack: "g-base"
      num_sampled_graphs: 8
      sampling_strategy: "model-independent"
      offline: True
      threshold_scale_factor: 0.9
      prior: 0.5
