---
cora-GCN:
  dataset: "cora"
  model: "GCN"
  epochs: 15
  hidden_dim:
  - 32
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  max_num_nodes: 10000
  num_target_nodes: -1
  num_audits: 100
  target_fpr:
  - 0.01
  - 0.001
  pretrain_shadow_models: False
  num_shadow_models: 10
  seed: 0
  attacks:
    bmia:
      attack: "bmia"
    lset:
      attack: "laplace-lset"
