---
lset-cora-GCN:
  attack: "lset"
  dataset: "cora"
  model: "GCN"
  epochs_target: 15
  epochs_shadow: 15
  num_experiments: 5
  hidden_dim_target: [32]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  num_shadow_models: 10
bootstrapped-lset-cora-GCN:
  attack: "bootstrapped-lset"
  dataset: "cora"
  model: "GCN"
  epochs_target: 15
  epochs_shadow: 15
  num_experiments: 5
  hidden_dim_target: [32]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  num_shadow_models: 10
  num_sampled_graphs: 10
