---
cora-GCN:
  dataset: "cora"
  model: "GCN"
  epochs: 15
  hidden_dim: [32]
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  max_num_nodes: null
  num_target_nodes: 500
  num_audits: 10
  target_fpr: [0.01, 0.005]
  pretrain_shadow_models: True
  num_shadow_models: 20
  attacks:
    lset:
      attack: "lset"
    lira:
      attack: "lira"
    rmia:
      attack: "rmia"
      rmia_gamma: 2
