---
cora-GCN:
  dataset: "cora"
  model: "GCN"
  shadow_model: "GAT"
  epochs: 500
  shadow_epochs: 100
  batch_size: 8192
  hidden_dim:
  - 32
  shadow_hidden_dim:
  - 64
  lr: 0.01
  shadow_lr: 0.001
  weight_decay: 0.00001
  shadow_weight_decay: 0.0001
  dropout: 0.5
  max_num_nodes: null
  frac_target_nodes: 0.5
  train_frac: 0.35
  val_frac: 0.0
  num_audits: 10
  target_fpr:
  - 0.01
  - 0.001
  pretrain_shadow_models: True
  num_shadow_models: 8
  seed: 0
  attacks:
    MLP-attack-0hop:
      attack: "mlp-attack"
      mlp_attack_queries:
      - 0
      edge_dropout: 0.0
      mlp_hidden_dim:
      - 128
      - 64
    MLP-attack-comb:
      attack: "mlp-attack"
      mlp_attack_queries:
      - 0
      - 2
      edge_dropout: 0.5
      mlp_hidden_dim:
      - 128
      - 64
    lira:
      attack: "lira"
    rmia:
      attack: "rmia"
      rmia_gamma: 1
      Z_frac: 0.5
    lset:
      attack: "lset"
    graph-lset-MIA:
      attack: "graph-lset"
      num_sampled_graphs: 8
      sampling_strategy: "MIA"
      prior: 0.5
    lira-offline:
      attack: "lira"
      offline: True
    rmia-offline:
      attack: "rmia"
      rmia_gamma: 1
      Z_frac: 0.5
      offline: True
    lset-offline:
      attack: "lset"
      offline: True
    graph-lset-MIA-offline:
      attack: "graph-lset"
      num_sampled_graphs: 8
      sampling_strategy: "MIA"
      offline: True
      threshold_scale_factor: 0.9
      prior: 0.5
