---
LiRA-cora-GCN-transductive:
  attack: "lira"
  dataset: "cora"
  model: "GCN"
  epochs_target: 500
  hidden_dim_target: [32]
  num_shadow_models: 128
  query_hops: 2
  transductive: true
LiRA-cora-GCN-inductive:
  attack: "lira"
  dataset: "cora"
  model: "GCN"
  epochs_target: 500
  hidden_dim_target: [32]
  num_shadow_models: 128
  query_hops: 2
  transductive: false
