---
confidence-cora-GCN:
  attack: "confidence"
  dataset: "cora"
  model: "GCN"
  epochs_target: 500
  experiments: 200
  hidden_dim_target: [32]
  num_shadow_models: 128
  query_hops: [0, 2]
  transductive: false
  target_fpr: 0.005
lira-cora-GCN:
  attack: "lira"
  dataset: "cora"
  model: "GCN"
  epochs_target: 500
  experiments: 30
  hidden_dim_target: [32]
  num_shadow_models: 128
  query_hops: [0, 2]
  transductive: false
  target_fpr: 0.005
