---
basic-shadow-pubmed-GCN:
  attack: "basic-shadow"
  dataset: "pubmed"
  split: "sampled"
  model: "GCN"
  epochs_target: 500
  epochs_attack: 200
  hidden_dim_attack: [256, 64]
  batch_size: 32
confidence-pubmed-GCN:
  attack: "confidence"
  dataset: "pubmed"
  split: "sampled"
  model: "GCN"
  epochs_target: 500
LiRA-pubmed-GCN:
  attack: "lira"
  dataset: "pubmed"
  model: "GCN"
  epochs_target: 500
  num_shadow_models: 128
RMIA-pubmed-GCN:
  attack: "rmia"
  dataset: "pubmed"
  model: "GCN"
  epochs_target: 500
  num_shadow_models: 128
  rmia_offline_interp_param: 0.6