---
cora-GCN:
  dataset: "cora"
  model: "GCN"
  epochs: 15
  batch_size: 8192
  hidden_dim:
  - 32
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  max_num_nodes: null
  frac_target_nodes: 0.5
  train_frac: 0.5
  val_frac: 0.0
  num_audits: 10
  target_fpr:
  - 0.01
  - 0.001
  pretrain_shadow_models: True
  num_shadow_models: 8
  seed: 0
  attacks:
    bmia:
      attack: "bmia"
    lset:
      attack: "lset"
    lset-offline:
      attack: "lset"
      offline: True
    rmia:
      attack: "rmia"
      rmia_gamma: 
      Z_frac: 0.5
    rmia-gamma-2:
      attack: "rmia"
      rmia_gamma: 2
      Z_frac: 0.5
    rmia-offline:
      attack: "rmia"
      rmia_gamma: 1
      Z_frac: 0.5
      offline: True
    lira:
      attack: "lira"
    lira-offline:
      attack: "lira"
      offline: True
    MLP-attack-0hop:
      attack: "mlp-attack"
      mlp_attack_queries:
      - 0
      edge_dropout: 0.0
      mlp_hidden_dim:
      - 128
      - 64
    MLP-attack-comb:
      attack: "mlp-attack"
      mlp_attack_queries:
      - 0
      - 2
      edge_dropout: 0.5
      mlp_hidden_dim:
      - 128
      - 64
    confidence:
      attack: "confidence"
    graph-lset-MI:
      attack: "graph-lset"
      num_sampled_graphs: 8
      sampling_strategy: "model-independent"
      prior: 0.5
    graph-lset-MIA:
      attack: "graph-lset"
      num_sampled_graphs: 8
      sampling_strategy: "MIA"
      prior: 0.5
    graph-lset-MCMC:
      attack: "graph-lset"
      num_sampled_graphs: 8
      sampling_strategy: "MCMC"
      prior: 0.5
    graph-lset-MI-offline:
      attack: "graph-lset"
      num_sampled_graphs: 8
      sampling_strategy: "model-independent"
      offline: True
      threshold_scale_factor: 0.9
      prior: 0.5
