---
basic-shadow-chameleon-GAT:
  attack: "basic-shadow"
  dataset: "chameleon"
  split: "sampled"
  model: "GAT"
  epochs_target: 500
  epochs_attack: 200
  hidden_dim_attack: [256, 64]
  batch_size: 32
confidence-chameleon-GAT:
  attack: "confidence"
  dataset: "chameleon"
  split: "sampled"
  model: "GAT"
  epochs_target: 500
LiRA-chameleon-GAT:
  attack: "lira"
  dataset: "chameleon"
  model: "GAT"
  epochs_target: 500
  num_shadow_models: 128
RMIA-chameleon-GAT:
  attack: "rmia"
  dataset: "chameleon"
  model: "GAT"
  epochs_target: 500
  num_shadow_models: 128
  rmia_offline_interp_param: 0.1