---
Olatunji-cora-GCN:
  dataset: "cora"
  split: "TSTF"
  model: "GCN"
  batch_size: 32
  epochs_target: 50
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [100, 50]
  lr: 0.001
  dropout: 0.0
  query_hops: 1
  name: "Olatunji-cora-GCN"
Olatunji-citeseer-GCN:
  dataset: "citeseer"
  split: "TSTF"
  model: "GCN"
  batch_size: 32
  epochs_target: 30
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [100, 50]
  lr: 0.001
  dropout: 0.0
  query_hops: 1
  name: "Olatunji-citeseer-GCN"
Olatunji-cora-SAGE:
  dataset: "cora"
  split: "TSTF"
  model: "SAGE"
  batch_size: 32
  epochs_target: 30
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [100, 50]
  lr: 0.001
  dropout: 0.0
  query_hops: 1
  name: "Olatunji-cora-SAGE"
He-cora-SAGE:
  dataset: "cora"
  split: "disjoint"
  model: "SAGE"
  batch_size: 32
  epochs_target: 200
  epochs_attack: 500
  hidden_dim_target: 32
  hidden_dim_attack: [128]
  lr: 0.003
  dropout: 0.5
  query_hops: 2
  name: "He-cora-SAGE"
