---
basic-shadow-cora-GCN:
  attack: "basic-shadow"
  dataset: "cora"
  split: "sampled"
  model: "GCN"
  epochs_target: 200
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  batch_size: 32
  lr: 0.001
  dropout: 0.2
  query_hops: 0
confidence-cora-GCN:
  attack: "confidence"
  dataset: "cora"
  split: "sampled"
  model: "GCN"
  epochs_target: 200
  hidden_dim_target: 256
  lr: 0.001
  dropout: 0.2
  query_hops: 0
LiRA-cora-GCN:
  attack: "lira"
  dataset: "cora"
  model: "GCN"
  epochs_target: 200
  hidden_dim_target: 256
  num_shadow_models: 128
  lr: 0.001
  dropout: 0.2
  query_hops: 0
RMIA-cora-GCN:
  attack: "rmia"
  dataset: "cora"
  model: "GCN"
  epochs_target: 200
  hidden_dim_target: 256
  num_shadow_models: 128
  lr: 0.001
  dropout: 0.2
  query_hops: 0
  rmia_offline_interp_param: 0.6
