---
lira-corafull-GCN:
  attack: "lira"
  dataset: "corafull"
  model: "GCN"
  epochs_target: 500
  experiments: 10
  hidden_dim_target: [512]
  num_shadow_models: 64
  query_hops: [0, 2]
  transductive: false
  target_fpr: 0.0005
  lr: 0.001
  weight_decay: 0.00001
  dropout: 0.5
confidence-corafull-GCN:
  attack: "confidence"
  dataset: "corafull"
  model: "GCN"
  epochs_target: 500
  experiments: 10
  hidden_dim_target: [512]
  query_hops: [0, 2]
  transductive: false
  target_fpr: 0.0005
  lr: 0.001
  weight_decay: 0.00001
  dropout: 0.5
