---
cora-GCN:
  dataset: "cora"
  split: "sampled"
  model: "GCN"
  batch_size: 32
  epochs_target: 100
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  lr: 0.001
  dropout: 0.2
  query_hops: 1
  name: "cora-GCN"
citeseer-GCN:
  dataset: "citeseer"
  split: "sampled"
  model: "GCN"
  batch_size: 32
  epochs_target: 30
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  lr: 0.001
  dropout: 0.2
  query_hops: 1
  name: "citeseer-GCN"
pubmed-GCN:
  dataset: "pubmed"
  split: "sampled"
  model: "GCN"
  batch_size: 32
  epochs_target: 100
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  lr: 0.001
  dropout: 0.2
  query_hops: 1
  name: "pubmed-GCN"
corafull-GCN:
  dataset: "corafull"
  split: "sampled"
  model: "GCN"
  batch_size: 32
  epochs_target: 30
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  lr: 0.001
  dropout: 0.2
  query_hops: 1
  name: "corafull-GCN"
flickr-GCN:
  dataset: "flickr"
  split: "sampled"
  model: "GCN"
  batch_size: 32
  epochs_target: 30
  epochs_attack: 100
  hidden_dim_target: 256
  hidden_dim_attack: [128, 64]
  lr: 0.001
  dropout: 0.2
  query_hops: 1
  name: "flickr-GCN"
