---
default-parameters:
  dataset: "cora"
  model: "GCN"
  batch_size: 32 # Only used for MLP attack
  epochs: 15
  epochs_mlp: 500
  num_audits: 1
  max_num_nodes: null
  num_target_nodes: -1 # -1 uses all nodes
  hidden_dim: [32]
  hidden_dim_mlp: [128]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  early_stopping: 0
  datadir: "./data"
  hyperparam_search: False
  optimizer: "Adam"
  inductive_split: True
  inductive_inference: True
  train_frac: 0.5
  val_frac: 0.0
  seed: 0
  num_processes: 1
