---
default-parameters:
  dataset: "cora"
  model: "GCN"
  epochs: 15
  num_experiments: 1
  max_num_nodes: null
  num_target_nodes: 500 # -1 uses all nodes
  hidden_dim: [32]
  target_fpr: 0.01
  lr: 0.01
  weight_decay: 0.0001
  dropout: 0.5
  early_stopping: 0
  datadir: "./data"
  hyperparam_search: False
  optimizer: "Adam"
  inductive_split: True
  inductive_inference: True
  train_frac: 0.5
  val_frac: 0.0
  seed: 0
  num_processes: 1
