name: conda_env_cpu
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.12
- pytorch=2.3.1
- pytorch-cuda=11.8
- pip
- numpy
- matplotlib
- scikit-learn
- scipy
- pandas
- pip:
  - torch_geometric==2.6.0
  - laplace-torch
  - torchmetrics
  - tqdm
  - PyYAML
