name: conda_env_cpu
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pip
- numpy
- matplotlib
- scikit-learn
- scipy
- pandas
- pip:
  - torch==2.2.0+cu118
  - torchvision==0.17.0+cu118
  - torch_geometric
  - pyg_lib
  - torch_scatter
  - torch_sparse
  - -f https://download.pytorch.org/whl/torch_stable.html
  - -f https://data.pyg.org/whl/torch-2.2.0+cu118.html
  - laplace-torch
  - torchmetrics
  - tqdm
  - PyYAML
  - optuna
